<?php
/**
 * Copyright © Wheelpros, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Wheelpros\Checkout\Block\Html\Header
 */
?>
<header class="header">
    <div class="page__section">
        <?= $block->getChildHtml('wheelpros.checkout.header.breadcrumbs'); ?>
        <div class="headline">
            <h1 class="page__title headline__left"><?= $block->escapeHtml($block->getCheckoutTitle()); ?></h1>
            <div id="authentication" data-bind="scope:'authentication'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <script type="text/x-magento-init">
            {
                "#authentication": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
            </script>
        </div>
    </div>
</header>
