<?php

?>
<?php
// @codingStandardsIgnoreFile
/** @var \Wheelpros\ExtendedShippingMethods\Block\Adminhtml\Form\Field\MethodsConfiguration $block */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?= $block->escapeHtmlAttr($_htmlId) ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= $block->escapeHtmlAttr($block->getElement()->getId()) ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?= $block->escapeHtml($column['label']) ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?= (int)$colspan ?>"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="<?= count($block->getColumns())+(int)$colspan ?>" class="col-actions-add">
                    <button id="addToEndBtn<?= $block->escapeHtmlAttr($_htmlId); ?>" class="action-add" title="<?= $block->escapeHtmlAttr(__('Add')); ?>" type="button">
                        <span><?= $block->escapeHtml($block->getAddButtonLabel()) ?></span>
                    </button>
                </td>
            </tr>
            </tfoot>
            <tbody id="addRow<?= $block->escapeHtmlAttr($_htmlId); ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?= $block->escapeHtmlAttr($block->getElement()->getName()); ?>[__empty]" value="" />

    <script>
        require([
            'mage/template',
            'prototype'
        ], function (mageTemplate) {
            // create row creator
            window.arrayRow<?= $block->escapeHtmlAttr($_htmlId) ?> = {

                // define row prototypeJS template
                template: mageTemplate(
                    '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    + '<td>'
                    + '<?= /* @noEscape */ $block->renderCellTemplate($columnName) ?>'
                    + '<\/td>'
                    <?php endforeach; ?>

                    <?php if ($block->isAddAfter()): ?>
                    + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?= $block->escapeHtml(__('Add after')); ?><\/span><\/button><\/td>'
                    <?php endif; ?>

                    + '<td class="col-actions"><button onclick="arrayRow<?= $block->escapeHtmlAttr($_htmlId); ?>.del(\'<%- _id %>\')" class="action-delete" type="button"><span><?= $block->escapeHtml(__('Delete')); ?><\/span><\/button><\/td>'
                    +'<\/tr>'
                ),

                add: function(rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // Prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                            <?php foreach ($block->getColumns() as $columnName => $column): ?>
                            <?= $block->escapeHtml($columnName) ?>: '',
                                'option_extra_attrs': {},
                            <?php endforeach; ?>
                            _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                        };
                    }

                    // Insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert($('addRow<?= $block->escapeHtmlAttr($_htmlId); ?>'), {bottom: this.template(templateValues)});
                    }

                    // Fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        var BP = '<?= $block->escapeUrl($block->getBaseImagePath()); ?>';
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                var imagePath = rowData.column_values[rowInputElementNames[i]];
                                if (rowInputElementNames[i] === (rowData.methods_id + '_image') && imagePath) {
                                    $(rowInputElementNames[i] + '_placeholder').insert({
                                        top: new Element(
                                            'img',
                                            {
                                                src: BP + imagePath,
                                                alt: imagePath,
                                                width: '64px'
                                            }
                                        )
                                    });
                                    $(rowInputElementNames[i] + '_old').setValue(rowData.column_values[rowInputElementNames[i]]);
                                } else {
                                    $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);
                                }
                            }
                        }
                    }

                    // Add event for {addAfterBtn} button
                    <?php if ($block->isAddAfter()): ?>
                    Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
                    <?php endif; ?>
                },

                del: function(rowId) {
                    $(rowId).remove();
                }
            };

            // bind add action to "Add" button in last row
            Event.observe('addToEndBtn<?= $block->escapeHtmlAttr($_htmlId); ?>', 'click', arrayRow<?= $block->escapeHtmlAttr($_htmlId); ?>.add.bind(arrayRow<?= $block->escapeHtmlAttr($_htmlId) ?>, false, false));

            // add existing rows
            <?php
            foreach ($block->getArrayRows() as $_rowId => $_row) {
                echo "arrayRow{$block->escapeHtmlAttr($_htmlId)}.add(" . /** @noEscape */ $_row->toJson() . ");\n";
            }
            ?>

            // Toggle the grid availability, if element is disabled (depending on scope)
            <?php if ($block->getElement()->getDisabled()):?>
            toggleValueElements({checked: true}, $('grid<?= $block->escapeHtmlAttr($_htmlId); ?>').parentNode);
            <?php endif;?>
        });
    </script>
</div>
